### Registrar usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "nombre": "Idiar",
    "apellido": "Chacin",
    "username": "IdiaRj",
    "correo": "idiar16@gmail.com",
    "password": "16012004"
}

### Logear un usuario
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Idiarj",
    "password": "16012004"
}

### Home
GET http://localhost:3000/home

