### Ver carpetas del usuario logeado
GET http://localhost:3000/folder/getFolders

### Crear una carpeta
POST http://localhost:3000/folder/createFolder
Content-Type: application/json

{
    "folderName": "Carpeta de Idiar"
}

### Actualizar carpeta
PUT http://localhost:3000/folder/updateFolder/3
Content-Type: application/json

{
    "newFolderName": "Carpeta de Odiar"
}

### Ver notas de una carpeta
GET http://localhost:3000/folder/getNotes/3

### Borrar una carpeta
DELETE http://localhost:3000/folder/deleteFolder/3